export const Path = {
  // Social
  Login: "/login",
  SignUp: "/register",
  GetAllPosts: "/post",
  GetTotalPosts: "/post/total",
  GetPostDetails: "/post",
  GetPostByUserId: "/post/user",
  GetDetailUser: "/user",
  GetTotalUser: "/users/total",
  GetAllNotifications: "/notify/user",
  LoadMoreNotifications: "/notify/load-more/user",
  GetAllFriendSuggest: "/friend/suggest",
  GetAllFriend: "/friend",
  GetAllFriendRequestSending: "/friend/send",
  GetAllFriendRequestReceived: "/friend/receive",
  LikePost: "/post/like",
  CreatePost: "/post",
  DeletePost: "/post",
  UpdatePost: "/post",
  CreateCommentPost: "/post/comment",
  CreateNotification: "/notify",
  UpdateCommentPost: "/post/comment",
  DeleteCommentPost: "/post/comment",
  DeleteAllNotification: "/notify",
  UpdateUserProfile: "/user/update",
  UpdateUserPassword: "/user/changepassword",
  UpdateReadAllNotification: "/notify/read-all",
  SendFriendInvitation: "/friend",
  AcceptFriendInvitation: "/friend",
  CancelFriendInvitation: "/friend",
  DeleteFriend: "/friend",
  SharePost: "/post/share",
  UnSharePermanentPost: "/post/share/force",
  UploadPostImage: "/files/posts",
  UploadAvatarImage: "/files/avatar",
  GetAllPostInTrashByUserId: "/post/user/trash",
  ReplyCommentPost: "/post/comment/reply",
  SearchPost: "/post/search",
  UploadCommentImage: "files/comments",
  GetAllNotificationsNotRead: "/notify/not-read/user",
  CountAllNotificationsNotRead: "/notify/not-read/user/count",

  // Courses
  GetAllUser: "/users",
  GetAllCourses: "/courses",
  GetTotalCourse: "/courses/total",
  StatisticCourse: "/courses/statistic-course",
  GetTotalCourseByUser: "/courses/total-by-user",
  GetAllCoursesNotPagination: "/courses/all",
  GetAllHashTag: "/courses/hash-tag",
  RegisterCourse: "/courses/register",
  GetAllChapters: "/chapters",
  GetAllChaptersByCourse: "/chapters/chapter-by-course",
  GetAllChaptersNotPagination: "/chapters/all",
  GetAllLessons: "/lessons",
  GetAllLessonsByChapter: "/lessons/lesson-by-chapter",
  GetAllStudyPaths: "/study/route",
  GetTotalStudyPaths: "/study/route/total",
  GetAllStudyPathsNotPagination: "/study/route/all",
  GetProgressLearn: "/progress",
  GetAllConversation: "/conversation",
  SendMessage: "/conversation",
  Chat: "/message",
  BlockUser: "/user/block",
  UnBlockUser: "/user/unblock",
  CreateGallery: "/images",
  DeleteGallery: "/images",

  // ChatGPT
  ChatGPTApi: "https://api.openai.com/v1/chat/completions",
  GetConversationChatGPTDetail: "/chatgpt-conversation",
  CreateMessageChatGPT: "/chatgpt-message",
};

export const BASE_URL_SOCKET_SERVER = "http://localhost:8080/rest/ws";
export const BASE_URL_SERVER = "http://localhost:8080/rest/api";

export const LOCALES_NAME = "locales_name";
