package com.b2012149.lv.enumType;

public enum FriendActionType {
	ADD_FRIEND_REQUEST_ACTION, ACCEPT_FRIEND_REQUEST_ACTION, DECLINE_FRIEND_REQUEST_ACTION,
	CANCEL_FRIEND_REQUEST_SENDING_ACTION, REMOVE_FRIEND_ACTION,
}
